export var companyName = 'داده پردازی نیک آسا فام'
export var economyNumber = '411557846496'
export var nationalNumber = '14006917382'
export var postalCode = '1651736143'
export var companyAddress = 'تهرانپارس خیابان گلبرگ شرقی نبش خیابان ۱۱۳ مجتمع نگین گلبرگ پلاک ۶۱ واحد ۲'
export var companyTel = '۰۲۱-۷۷۷۳۵۲۲۴'
export var tehranLabel = `تهران`
export var versionLabel = `نسخه`
export var InnerCode_InvalidAreaMsg =  ` تعیین محله کسب و کار ضروری است`
export var InnerCode_EntityNotFoundMsg = `موجودیت موردنظر شما در سمت سرور وجود ندارد`
export var InnerCode_InvalidNameMsg =  ` نام شرکت/مغازه ضروری است`
export var InnerCode_EmptyPhoneListMsg= `می بایست حداقل یک شماره تلفن وارد شود`
export var InnerCode_MobileOrTelNumberNotFoundMsg = `می بایست حداقل یک شماره تلفن وارد شود`
export var InnerCode_InvalidFirstNameMsg = `فیلد نام ضروری است و باید بین 2 تا 50 کاراکتر باشد`
export var InnerCode_InvalidLastNameMsg = `فیلد نام خانوادگی ضروری است و باید بین 2 تا 50 کاراکتر باشد`
export var InnerCode_InvalidTitleMsg = `فیلد عنوان کسب و کار ضروری است و باید بین 2 تا 50 کاراکتر باشد`
export var InnerCode_InvalidJobcat1Msg = `حداقل باید یک رسته شغلی انتخاب شود`
export var InnerCode_InvalidJobcat2Msg =  `حداقل باید یک شغل انتخاب شود`
export var InnerCode_InvalidJobcat3Msg =  `حداقل باید یک تخصص انتخاب شود`
export var InnerCode_EmptyJobsListMsg = `حداقل یک شغل باید وارد شود`
export var InnerCode_RepeatedWorkStationTitleMsg = `عنوان کسب و کار نباید تکراری باشد`
export var InnerCode_InvalidStoreLicenseDateMsg = `تاریخ اخذ جواز وارد شده معتبر نیست`
export var InnerCode_UnableToDeleteFileMsg = `امکان حذف فایل وجود ندارد`
export var InnerCode_InvalidJobPricePercentMsg = `فیلد درصد پرداختی بابت ارجاع کارها نامعتبر است`
export var InnerCode_InvalidNotificationPercentMsg = `فیلد درصد ارجاعات نامعتبر است`
export var InnerCode_InvalidNotificationPriceMsg = `فیلد قیمت هر ارجاع نامعتبر است`
export var InnerCode_InvalidPriceMsg = `فیلد قیمت پایه سرویس نامعتبر است`
export var InnerCode_InvalidPostalCodeMsg = `فیلد کد پستی نامعتبر است`
export var InnerCode_InvalidTelegramMsg = `فیلد شناسه تلگرام معتبر نیست`
export var InnerCode_InvalidOfficeRegisterNumberMsg = `شماره ثبت شرکت معتبر نیست`
export var InnerCode_InvalidInstagramMsg = `فیلد شناسه اینستاگرام معتبر نیست`
export var InnerCode_InvalidOfficeNationalCodeMsg = `شماره ملی شرکت باید 11 رقم باشد`
export var InnerCode_InvalidStoreLicenseNumberMsg = `شماره جواز مغازه معتبر نیست`
export var InnerCode_InvalidNationalCodeMsg = `کد ملی معتبر نیست`
export var InnerCode_InvalidWorkTypeMsg = `نوع کسب و کار نامعنبر است`
export var InnerCode_DuplicateEntityMsg = `این موجودیت قبلا ثبت شده است`
export var InnerCode_InvalidCodeMsg = `کد وارد شده صحیح نمی باشد`
export var InnerCode_InvalidWCodeMsg = `کد متخصص وارد شده صحیح نمی باشد`
export var InnerCode_InvalidPositionTypeMsg = `سمت وارد شده صحیح نمی باشد`
export var InnerCode_InvalidWorkstationMsg = `اطلاعات کسب و کار صحیح نمی باشد`
export var InnerCode_InvalidUserDataMsg = `اطلاعات کاربری صحیح نمی باشد`
export var InnerCode_InvalidOwnerIdMsg = `شناسه نماینده کسب و کار معتبر نیست`
export var InnerCode_InvalidBirthYearMsg = `سال تولد معتبر نیست`
export var InnerCode_InvalidPhotoMsg = `آدرس عکس وارد شده معتبر نیست`
export var InnerCode_ThisUserIsAlreadyWorkerMsg = `حساب کاربری وارد شده متخصص است`
export var InnerCode_InvalidFilterStartDateMsg = `زمان شروع فیلتر معتبر نیست`
export var InnerCode_InvalidFilterStopDateMsg = `زمان پایان فیلتر معتبر نیست`
export var InnerCode_InvalidTimeMsg = `زمان وارد شده معتبر نیست`
export var InnerCode_invalidCitylMsg = `شهر وارد شده معتبر نیست`
export var InnerCode_invalidRegionlMsg = `منطقه وارد شده معتبر نیست`
export var InnerCode_invalidAreaMsg = `محله وارد شده معتبر نیست`
export var InnerCode_DocumentIsNotDeletableMsg = `امکان حذف مدرک اجباری وجود ندارد`
export var InnerCode_UserIsWorkStationOwnerMsg = `این کاربر مالک کسب و کار است`
export var InnerCode_UserIsWorkerMsg = `این کاربر به عنوان سرویس کار تعریف شده است`
export var InnerCode_WsHaveSomeWorkersMsg = `این کسب و کار دارای تعدادی سرویس کار است`
export var InnerCode_InvalidTransaction_LowCreditMsg = `اعتبار کافی نیست`
export var InnerCode_Relation2BothWrAndWsMsg = `یک مدرک نمی تواند هم به کسب و کار و هم به متخصص مرتبط باشد`
export var InnerCode_NoRelation2WrOrWsMsg = `نوع مدرک باید مرتبط به کسب و کار یا متخصص باشد`
export var InnerCode_InvalidRegisterStateMsg = `وضعیت ثبت نام معتبر نیست`
export var InnerCode_InvalidDocumentTypeMsg = `نوع مدرک معتبر نیست`
export var InnerCode_DuplicateDocumentTypeMsg = `این نوع مدرک پیش از این ثبت شده است`
export var InnerCode_InvalidRequestStateMsg = `وضعیت درخواست نامعتبر است`
export var InnerCode_RequestCancelNotPermitedMsg = `امکان لغو این درخواست وجود ندارد`
export var InnerCode_InvalidCreditSerachMsg = `اعتبار وارد شده معتبر نیست`
export var InnerCode_EmptyEntityENameMsg = `نام لاتین باید تکمیل شود`
export var InnerCode_DuplicateEntityENameMsg  = `نام لاتین نمی تواند تکراری باشد`
export var InnerCode_InvalidDiscountPercentMsg = 'درصد کد تخفیف معتبر نیست'
export var InnerCode_InvalidDiscountMaxCreditMsg = 'حداکثر اعتبار کد تخفیف معتبر نیست'
export var InnerCode_InvalidDiscountTotalCntMsg = 'تعداد کل دفعات استفاده از کد تخفیف معتبر نیست'
export var InnerCode_InvalidDiscountDescriptionMsg = 'توضیحات مربوط به کد تخفیف معتبر نیست'
export var InnerCode_InvalidCommissionOnIvoiceItemsMsg = 'کارمزد اقلام فاکتور معتبر نیست'
export var InnerCode_InvalidCommissionOnTransferMsg = 'کارمزد هزینه ایاب و ذهاب معتبر نیست'
export var InnerCode_InvalidCommissionOnWageMsg = 'کارمزد دستمزد معتبر نیست'
export var InnerCode_InvalidSnoozeStateMsg = "این درخواست قابل تمدید نمیباشد"
export var InnerCode_RequestStateIsClosedMsgMsg = 'درخواست به اتمام رسیده است'
export var InnerCode_AlreadyRegisteredMsg = 'ثبت سند قبلا انجام شده است'
export var InnerCode_InvalidAccountantNumberMsg = 'شماره سند معتبر نیست'
export var InnerCode_InvalidDiscountTypeMsg = 'نوع کد تخفیف معتبر نیست'
export var InnerCode_InvalidDiscountSourceTypeMsg = 'منبع کد تخفیف معتبر نیست';
export var InnerCode_Cat3HaveAlreadyGeneralDescountMsg = 'برای این تخصص قبلا کد تخفیف عمومی تعریف شده است'
export var InnerCode_Cat3HaveAlreadyFirstDescountMsg = 'برای این تخصص قبلا کد تخفیف تعریف شده است'
export var InnerCode_InvalidRegisterTime = 'زمان ثبت معتبر نیست'
export var projectTitle : string = 'سامانه مدیریتی پالسین '
export var userNameLabel = `UserName`   
export var passwordLabel = `Password`
export var userNameLabelFa = `شناسه کاربری`
export var passwordLabelFa = `رمز عبور`

export var docTypeLabelFa = `نوع مدرک`
export var subTypeLabelFa = `نوع اشتراک`
export var workTypeLabelFa = `نوع کسب و کار`
export var requiredForStoreLabel = `مربوط به مغازه ها`
export var requiredForLegalLabel = `مربوط به کسب و کارهای حقوقی`
export var requiredForRealLabel = `مربوط به کسب و کارهای حقیقی`
export var requiredForWorkerLabel = `مربوط به متخصص `
export var duplicatedAllowed = `امکان ثبت تکراری`

export var pwdLabelFa = `رمز عبور`  
export var oldPWDLabelFa = `رمز عبور پیشین`
export var newPWDLabelFa = `رمز عبور جدید`
export var rePWDLabelFa = `تکرار رمز عبور`
export var roleLabelFa = `سطح دسترسی`
export var saveLabelFa = `ذخیره`
export var delLabelFa = `حذف`
export var editLabelFa=`ویرایش`
export var createNewUser = `ایجاد حساب کاربری جدید`
export var createNewDocType = `ایجاد نوع مدرک جدید`
export var createNewSubType = `ایجاد نوع اشتراک جدید`
export var createNewWorkType = `ایجاد نوع کسب و کار جدید`
export var createNewWorkStation = `ایجاد کسب و کار جدید`
export var NewWorkStation = `کسب و کار جدید`

export var confirmHeader = `تایید عملیات`
export var confirmText = `آیا مطمین به ادامه عملیات هستید؟`
export var actionLabel = `کنترل`
export var errorLabel = `خطا`
export var warningLabel = `اخطار`
export var noLabel = `خیر`
export var yesLabel = `بله`
export var refreshLabel = `بروز رسانی`
export var systemUsersLabel = `کاربران پورتال`
export var editPanelLabel = `فرم ویرایش اطلاعات`
export var userNameValidMsg = `فیلد نام کاربری ضروری است`
export var userNameInvalidMsg = `نام کاربری معتبر نیست `
export var userNamePolicyMsg = `نام کاربری باید حداقل 5 کاراکتر و حداکثر 20 کاراکتر باشد `
export var userNameDuplicatedMsg = `نام کاربری تکراری است`
export var workstationTitleDuplicatedMsg = `نام کسب و کار تکراری است`
export var passwordInvalidMsg = `رمز عبور نامعتبر است` 
export var passValidMsg = `فیلد رمز عبور ضروری است`
export var roleValidMsg = `فیلد سطح دسترسی ضروری است`
export var docValidMsg = `فیلد نام مدرک ضروری است`
export var docinValidMsg = `فیلد نام مدرک باید حداقل شامل دو کاراکتر باشد`
export var InnerCode_InvalidDocumentInfoMsg = `فیلد نام مدرک نامعتبر است`
export var roleInvalidMsg = `فیلد سطح دسترسی نامعتبر است`
export var oldPasswordInvalid = `رمز عبور قبلی نادرست است`
export var passNotTheSame = `رمزهای وارد شده با هم مطابقت ندارند`
export var userNameNotExistedMsg = `اطلاعات مورد نظر شما در سرور وجود ندارد`
export var ChangePassPanelLabel = ` تغییر رمز عبور`
export var showChangePassPanelLabel = `فرم تغییر رمز عبور`
export var loginBtnLabel = `ورود`
export var invalidLoginMsg = `نام کاربری یا رمز عبور صحیح نمی باشد`
export var invalidLoginRole  = `حساب کاربری شما مجوز دسترسی به پنل سیستمی را ندارد`
export var unableToConnectBackEnd = `امکان اتصال به سرور وجود ندارد`
export var badRequestMsg = `قالب درخواست ارسالی به سرور ناصحیح است`
export var sessionExpiredMsg  =`دسترسی شما منقضی شده است`
export var EmptyEntityNameMsg = `اطلاعات مورد نظر شما در سرور وجود ندارد`
export var InvalidEntityNameMsg = `درخواست شما نامعتبر است`
export var RepeatedEntityNameMsg = `فیلد وارد شده تکراری است`
export var EntityHaveChildMsg = `فیلد مورد نظر دارای تعدادی زیر گروه است`
export var InnerCode_EmptyCityListMsg = 'لیست شهرهای فعال خالی است'
export var InnerCode_InvalidCommisionOffset = 'قیلد آفست کمیسیون ضروری است'
export var waitMsg = `لطفا منتظر بمانید`
export var dateTitle =' 24 اردیبهشت '
export var searchLabel = `بین کسب و کارها جستجو کنید`
export var contactUS = `تماس با ما` 
export var aboutUS = `درباره ما`
export var menuItem1Label = `صفحه نخست`
export var menuItem2Label = `مدیریت محتوا`
export var menuItem2SubItem1Label = `تقسیم بندی کشوری`
export var menuItem2SubItem2Label = ` انواع کسب و کار`
export var menuItem2SubItem3Label = `دسته بندی شغلی`
export var menuItem2SubItem4Label = ` انواع مدارک`
export var menuItem2SubItem5Label = ` انواع اشتراک`
export var menuItem9SubItem1Label = `پراکندگی جغرافیایی `
export var geoReportLabel = `گزارش پراکندگی جغرافیایی مشاغل`
export var menuItem3Label = `مدیریت سیستمی`
export var userMgmLabel = `مدیریت کاربران`
export var menuItem3SubItem1Label = `مدیریت کاربران پورتال`
export var menuItem3SubItem2Label = `مدیریت نسخه های اپ` 
export var menuItem4Label = `مدیریت کسب و کارها`
export var menuItem5Label = `بررسی اطلاعات` 
export var menuItem6Label = `مدیریت مالی`
export var menuItem6SubItem1Label = `گزارش تراکنش های مالی`
export var menuItem6SubItem2Label = `مدیریت مالی متخصصین`
export var menuItem6SubItem3Label = `مدیریت مالی کاربران`
export var menuItem6SubItem4Label = 'گزارش حسابداری متخصصین'
export var menuItem7Label = `مدیریت قرعه کشی`
export var menuItem10Label = `مدیریت درخواستها`
export var menuItem9Label = `گزارشات`
export var menuItem8Label = `خروج`

export var jobCategory1Label = `تاسیسات`
export var jobCategory2Label = `عمران`
export var jobCategory3Label = `لوازم خانه`
export var jobCategory4Label = `دکوراسیون`
export var jobCategory5Label = `امور رفاهی`
export var jobCategory6Label = `گل و گیاه`

export var totalRegisteredLabel = ` کسب و کارهای ثبت شده`
export var totalRequestedLabel = ` درخواستها `
export var totalRegisteredRequestLabel = 'درخواستهای ثبت شده'
export var totalCanceledRequestLabel = 'درخواستهای لغو شده'
export var footerText = `تمام حقوق مادی و معنوی پالسین به شرکت داده پردازی نیک آسا تعلق دارد`
export var nameLabel = `نام`
export var fnameLabel = `نام فارسی`
export var latinNameLabel = `نام لاتین`
export var bizNameLabel = `نام کسب و کار`
export var required = `الزامی`
export var requiredMsg = `این پارامتر الزامی است`
export var loginHeader = `ورود به سیستم`
export var iranLabel = `ایران`
export var addProvinceLabel = `اضافه کردن استان`
export var editProvinceLabel = `ویرایش استان`
export var deleteProvinceLabel = `حذف استان`

export var addTownshipLabel = `اضافه کردن شهرستان`
export var editTownshipLabel = `ویرایش شهرستان`
export var deleteTownshipLabel = `حذف شهرستان`

export var addCityLabel = `اضافه کردن شهر`
export var editCityLabel = `ویرایش شهر` 
export var deleteCityLabel = `حذف شهر`

export var addRegionLabel = `اضافه کردن منطقه`
export var editRegionLabel = `ویرایش منطقه`
export var deleteRegionLabel = `حذف منطقه`


export var addAreaLabel = `اضافه کردن محله`
export var editAreaLabel = `ویرایش محله`
export var deleteAreaLabel = `حذف محله`

export var listProvinceLabel = `لیست استانها`
export var listTownshipLabel = `لیست شهرستانهای ` 
export var listCityLabel = `لیست شهرهای`
export var listRegionLabel = `لیست مناطق`
export var listAreaLabel = `لیست محلات`
export var chooseProvinceMsg = `استان را انتخاب کنید`
export var chooseTownshipMsg = `شهرستان را انتخاب کنید`
export var chooseCityMsg = `شهر را انتخاب کنید`
export var chooseRegionLabel = 'منطقه را انتخاب کنید'
export var chooseAreaMsg = `محله را انتخاب کنید`
export var allRegionLabel = `همه مناطق`
export var allJC2Label = `همه شغل ها`
export var allJC3Label = `همه تخصص ها`
export var allRegisterState = `همه وضعیت ها`
export var allClientsLabel = 'همه کاربران'
export var emptyListMsg = `لیست موردنظر شما خالی است`
export var emptyProvinceListMsg = `استانی تا کنون ثبت نشده است`
export var emptyRegionListMsg = `منطقه ای برای شهر انتخابی شما ثبت نشده است`
export var emptyCityListMsg = `شهری برای شهرستان انتخابی شما ثبت نشده است`
export var emptyTownshipListMsg = `شهرستانی برای استان انتخابی شما ثبت نشده است`
export var emptyAreaListMsg = `محله ای برای منطقه انتخابی شما ثبت نشده است`
export var chooseJC1Msg = `رسته شغلی را انتخاب کنید`
export var chooseJC2Msg = ` شغل را انتخاب کنید`
export var chooseJC3Msg = `تخصص را انتخاب کنید`
export var addNewProvinceMsg = `استان جدید به پایگاه داده اضافه شد`
export var addNewTownshipMsg = `شهرستان جدید به پایگاه داده اضافه شد`
export var addNewCityMsg = `شهر جدید به پایگاه داده اضافه شد`
export var addNewRegionMsg = `منطقه جدید به پایگاه داده اضافه شد`
export var addNewAreaMsg = `محله جدید به پایگاه داده اضافه شد`

export var removeProvinceMsg = `استان مورد نظر از پایگاه داده حذف شد`
export var removeTownshipMsg = `شهرستان مورد نظر از پایگاه داده حذف شد`
export var removeCityMsg = `شهر مورد نظر از پایگاه داده حذف شد`
export var removeRegionMsg = `منطقه مورد نظر از پایگاه داده حذف شد`
export var removeAreaMsg = `محله مورد نظر از پایگاه داده حذف شد`

export var listJC1Label = `لیست رسته های شغلی`
export var listJC2Label = `لیست مشاغل`
export var listJC3Label = `لیست تخصص ها`
export var jc3Label = 'تخصص'
export var addJC1Label = `اضافه کردن رسته شغلی`
export var addJC2Label = `اضافه کردن شغل`
export var addJC3Label = `اضافه کردن تخصص`
export var editJC1Label = `ویرایش رسته شغلی`
export var editJC2Label = `ویرایش شغل`
export var editJC3Label = `ویرایش تخصص`
export var removeJC1Label = `حذف رسته شغلی`
export var removeJC2Label = `حذف شغل`
export var removeJC3Label = `حذف تخصص`
export var addNewJC1Msg = `رسته شغلی جدید به پایگاه داده اضافه شد`
export var addNewJC2Msg = `شغل جدید به پایگاه داده اضافه شد`
export var addNewJC3Msg = `تخصص جدید به پایگاه داده اضافه شد`
export var removeJC1Msg = `رسته شغلی مورد نظر از پایگاه داده حذف شد`
export var removeJC2Msg = `شغل مورد نظر از پایگاه داده حذف شد`
export var removeJC3Msg = `تخصص مورد نظر از پایگاه داده حذف شد`
export var emptyJC1ListMsg = `رسته شغلی تا کنون ثبت نشده است`
export var emptyJC2ListMsg = `شغلی برای رسته انتخابی شما ثبت نشده است`
export var emptyJC3ListMsg = `تخصصی برای شغل انتخابی شما ثبت نشده است`


export var msgNeedToCheck = `پیامهای نیاز به بررسی`
export var totalJobRegistered = `کسب و کارها`
export var totalUsers = `کاربران`
export var activeWorkerLabel = `متخصصین فعال`
export var verifiedWorkerLabel = `متخصصین تایید شده`
export var activeClientLabel = `کاربران فعال`

export var chooseFileLabel = `انتخاب فایل`
export var uploadLabel = `بارگزاری`
export var uploadImageLabel = `بارگزاری عکس`
export var cancelLabel = `لغو درخواست`
export var cancelReqLabel = `لغو `
export var closeReqLabel = 'اتمام درخواست'
export var uploadSuccessMsg = `بارگزاری فایل با موفقیت انجام شد`
export var invalidFileSize = `انداره فایل بیش از میزان مجاز است`
export var invalidFileSizeMessageDetail = `ماکزیمم اندازه فایل`
export var fileUploadServerErrMsg = `خطا در ارسال فایل`
export var basicDataErrMsg = `خطا در  بارگزاری اطلاعات اولیه`
export var byteLabel = `بایت`
export var sendLabel = `ارسال`
export var minLengthValidatorNameMsg = ` حداقل تعداد کاراکترهای مجاز برای این پارامتر `
export var maxLengthValidatorNameMsg = ` حداکثر تعداد کاراکترهای مجاز برای این پارامتر `
export var percentPatternMsg = `این فیلد عددی بین صفر تا 100 باید باشد` 
export var moneyPatternMsg = `این فیلد باید یک عدد صحیح مثبت باشد`
export var charLabel = `کاراکتر`
export var referenceLabel = 'ارجاع'
export var jobPricePercentLabel = `درصد پرداختی بابت اجرت کارها`
export var notificationPercentLabel = `درصد ارجاعات`
export var notificationPriceLabel = `قیمت هر ارجاع`
export var servicePriceLabel = `قیمت پایه سرویس`
export var rialLabel = `ریال`
export var numberLabel = `شماره`
export var typeLabel = `نوع`
export var workStationLabelFa = `نام کسب و کار`
export var firstNameLabel = `نام`
export var lastNameLabel = `نام خانوادگی`
export var nationalCodeLabel = `کد ملی`
export var positionLabel = `سمت`
export var genderLabel = `جنسیت`
export var officeNameLabel = `نام شرکت`
export var economyCodeLabel = 'شماره اقتصادی'
export var officeRegisterCodeLabel = `شماره ثبت`
export var officeNationalCodeLabel = `شناسه ملی`
export var officeRegisterDateLabel = `تاریخ ثبت`
export var storeNameLabel = `نام مغازه`
export var storeLicenseLabel = ` شماره جواز کسب `
export var storeRegisterDateLabel = `تاریخ اخذ جواز `
export var telLabel = `شماره تلفن`
export var mobileLabel = `شماره تلفن همراه`
export var appMobileLabel = `شماره تلفن همراه اپ`
export var phoneLabel = `شماره تلفن ثابت`
export var faxLabel = `شماره فکس `

export var mobileLabel2 = ` تلفن همراه`
export var phoneLabel2 = ` تلفن ثابت`
export var faxLabel2 = ` فکس `
export var registeredPhoneNumberList = `لیست شماره های ثبت شده`
export var registeredWorkJobList = `لیست شغل های ثبت شده`
export var emailLabel = `پست الکترونیکی`
export var instagramLabel = `شناسه اینستاگرام`
export var telegramLabel = `شناسه تلگرام`
export var webLabel = `آدرس وب سایت`
export var resourseLabel = `منبع `
export var registerResourseLabel = `منبع اطلاعاتی ثبت`
export var provinceLabel = `استان`
export var townshipLabel = `شهرستان`
export var cityLabel = `شهر`
export var regionLabel = `منطقه`
export var areaLabel = `محله`
export var addressLabel = `آدرس`
export var postalCodeLabel = `کد پستی`
export var mapLocationLabel = `موقعیت بر روی نقشه`
export var latitudeLabel = `عرض جغرافیایی`
export var longtitudeLabel = `طول جغرافیایی`
export var job_Category1Label = `رسته شغلی`
export var job_Category2Label = `شغل`
export var job_Category3Label = `تخصص`
export var aboutJobLabel = `درباره کسب و کار`
export var imageCatalogLabel = `کاتالوگ عکس`
export var bizCodeLabel = `کد کسب و کار` 
export var workerCodeLabel = `کد متخصص `
export var businessDataLabel = `اطلاعات عمومی کسب و کار`
export var personalWorkerDataLabel = ` اطلاعات فردی صاحب یا نماینده کسب و کار`
export var ownerLabel = `نماینده کسب و کار`
export var otherLabel = `شخص دیگری`
export var personalWorkerDataSumLabel = ` اطلاعات فردی`
export var companyDataLabel = `اطلاعات شرکت`
export var storeDataLabel = `اطلاعات مغازه`
export var contactDataLabel = `اطلاعات تماس`
export var locationDataLabel = `اطلاعات محل ثابت کسب و کار`
export var wlocationDataLabel = `اطلاعات محل ثابت متخصص`
export var rlocationDataLabel = `اطلاعات محل درخواست`
export var locationDataSumLabel = `اطلاعات مکانی`
export var jobDataLabel = `اطلاعات شغلی`
export var registerDataLabel = `  اطلاعات کاربر ثبت کننده`
export var verifyDataLabel = `  اطلاعات کاربر تایید کننده`
export var registerStateLabel = `وضعیت ثبت نام`
export var userAccountLabel = `اطلاعات حساب کاربری`
export var workerDataLabel = `اطلاعات متخصصین`
export var workerViewLabel = `اطلاعات متخصص`
export var clientViewLabel = `اطلاعات کاربر`
export var requestViewLabel = `اطلاعات درخواست`
export var transactionViewLabel = `اطلاعات تراکنش`
export var operationalViewLabel = `اطلاعات اجرایی`
export var discountViewLabel = `اطلاعات کد تخفیف`
export var singleLabel = 'تکی'
export var groupLabel = 'گروهی'
export var requestLocationViewLabel = `اطلاعات موقعیت مکانی درخواست`
export var workersLabel = `متخصصین`
export var clientsLabel = `کاربران`
export var locationOnMap = `موقعیت بر روی نقشه`
export var showLocationOnMap = `نمایش موقعیت بر روی نقشه`
export var specifyLocOnMap = `تعیین موقعیت بر روی نقشه`
export var showBzLabel = `نمایش لیست همه کسب و کارها`
export var showWorkerListLabel = `نمایش لیست متخصصین`
export var showBzStatLabel = `نمایش آمار مشاغل`
export var showLabel = `نمایش`
export var showDetialLabel = `نمایش جزییات`
export var showOnMap = `نمایش بر روی نقشه`
export var manLabel = `مرد` 
export var womanLabel = `زن`
export var emptyPhoneListMsg = `شماره تلفنی ثبت نشده است`
export var emptyWorkJobListMsg = `تخصصی ثبت نشده است`
export var invalidNumberMsg = `فرمت شماره صحیح نیست`
export var invalidPhoneMsg = `فرمت شماره تلفن صحیح نیست`
export var invalidMobileMsg = `فرمت شماره تلفن همراه صحیح نیست`
export var invalidFaxMsg = `فرمت شماره فکس صحیح نیست`
export var invalidNationalCodeMsg = `کد ملی صحیح نیست` 
export var invalidWebURLMsg = `فرمت آدرس وب سایت صحیح نیست`
export var invalidEmailMsg = `فرمت پست الکترونیکی صحیح نیست`
export var registerTimeLabel = `زمان ثبت`
export var depositTimeLabel = `زمان واریز`
export var updateTimeLabel = `زمان بروز رسانی`
export var registerWsUserName =  `کاربر ثبت کننده`
export var verifierWsUserName =  `کاربر تایید کننده`

export var nameStoreOrCompanyLabel = `نام شرکت یا مغازه`
export var registerBizLabel = `ثبت کسب و کار`
export var BizInfo = `اطلاعات کسب و کار`
export var showContactInfo = `نمایش اطلاعات تماس`
export var showLocationInfo = `نمایش اطلاعات محل ثابت کسب و کار`
export var showJobInfo = `نمایش اطلاعات شغلی`
export var showBizInfo = `نمایش اطلاعات کسب و کار`
export var showPersonalInfo = `نمایش اطلاعات فردی`
export var showFilter = `فیلتر`

export var repeatedPhoneNumberMsg = `شماره قبلا در لیست ثبت شده است`
export var repeatedWorkerJobMsg = `این اطلاعات شغلی قبلا در لیست ثبت شده است`
export var detailLabel = `جزییات`
export var changeLabel = `تغییرات`
export var allLabel = `همه`
export var editModeLabel = `حالت ویرایش`
export var activeLabel = `فعال`
export var bondLabel = 'سفته'
export var offerBlockLabel = 'ارسال پیشنهاد غیر فعال'
export var offerSendLabel = 'وضعیت ارسال پیشنهاد'
export var inactiveLabel = `غیر فعال`
export var relaxLabel = `استراحت`
export var clickToEdit = `جهت ویرایش بر روی فیلد مربوطه کلیک کنید`
export var selectToEdit = `جهت ویرایش بر روی رکورد مورد نظر کلیک کنید`
export var phoneRegisteredBeforeMsg = `تلفن وارد شده قبلا برای کسب و کارهای زیر ثبت شده است`
export var closeLabel = `بستن`
export var addLabel = `اضافه کردن`
export var operatorLabel = `اپراتور`
export var totalNumberLabel = `تعداد `
export var totalFilteredNumber = `تعداد موارد فیلتر شده`
export var successFullChangeMsg = `تغییرات با موفقیت انجام شد`

export var phoneEditMsg = `ویرایش تماس`
export var jobCategoryEditMsg = `ویرایش شغل`
export var invalidJobDataMsg = `اطلاعات شغلی صحیح نیست`
export var userLabel = 'کاربر'
export var registerUserLabel = `نام کاربر`

export var passwordPolicyHint = `رمز عبور باید حداقل 6 کارکتر باشد، شامل یک حرف یزرگ، حرف کوچک، عدد و کاراکترهای خاص باشد`
export var regionListCategory = `تقسیم بندی منطقه ای`
export var titleLabel = `عنوان`
export var contentLabel = 'متن'
export var vibrateLabel = 'لرزش'
export var soundLabel = 'صدا'
export var ledLabel = 'چشمک زن'
export var isBigLabel = 'نمایش اعلان بزرگ'

export var registeredBizCounter = `تعداد کسب و کارهای ثبت شده` 
export var doFilterLabel = `فیلتر کن`
export var chooseWorkTypeLabel = `نوع کسب و کار را انتخاب کنید`
export var chooseUserMsg = `نام کاربری را انتخاب کنید`
export var geReportMsg = ` دسته بندی شغلی را انتخاب کنید`
export var state  =`وضعیت`
export var serviceState = `وضعیت سرویس دهی`
export var verifiedLabel = `تایید شده`
export var unverifiedLabel = `تایید نشده` 
export var registerNewWorkerLabel = `ثبت متخصص`
export var noWorkerInWorkStation = `متخصصی برای این کسب و کار ثبت نشده است`
export var profileImageLabel = `تصویر پروفایل`
export var imageLabel = 'تصویر'
export var registerLabel = `ثبت`
export var editWorkerLabel = `ویرایش متخصص`
export var manageWorkerLabel = `مدیریت متخصصین`
export var wrPaymentReport = `گزارش اولیه تسویه حساب`
export var registerStatePhase1 = `ثبت نام نشده`
export var registerStatePhase2 = `ثبت نام اولیه`
export var registerStatePhase3 = `ثبت نام نهایی` 
export var birthYearLabel = `سال تولد`
export var chooseBirthYearLabel = `سال تولد خود را انتخاب کنید`
export var addNewUserLabel = `ثبت کاربر جدید`
export var changeWorkStationOwnerLabel = `تغییر نماینده کسب و کار`
export var expertsLabel = `مهارت های شغلی`
export var coverageAreaLabel = `شهرهای تحت پوشش`
export var documentLabel = `مدارک`
export var workingHoursLabel = `ساعت کاری`
export var removeAddWorkerJobMap = `حذف و اضافه مهارت های شغلی`
export var experienceStartLabel = `تجربه کاری`
export var chooseExperienceStartYearLabel = `سال شروع فعالیت خود را انتخاب کنید`
export var showPhotoLabel = `نمایش عکس`
export var tempUsers = `بروز وقفه/اشکال در ثبت نام`
export var descLabel = `توضیحات`
export var usedInApp = `بکار گرفته شده در برنامه`
export var otherPhoneNumber = `سایر شماره تلفنهای همراه متخصص`
export var documentsLabel = `مدارک`
export var registeredDocumentListLabel = `لیست مدارک ثبت شده`
export var registerNewDoc = `ثبت مدرک جدید`
export var registerActiveCity = 'ثبت شهر فعال جدید'
export var docListLabel = `لیست مدارک`
export var noImageForDoc = `تصویر مدرک بارگزاری نشده است`
export var chooseDocMsg = `نوع مدرک را انتخاب کنید`
export var chooseStateMsg = `انتخاب کنید`
export var repeatedAreaMsg = `محله انتخابی قبلا ثیت شده است`
export var repeatedRegionMsg = `شهر انتخابی قبلا ثیت شده است`
export var registerNewAreas = `ثبت شهر جدید`
export var serviceAreaList = `لیست شهرهای تحت پوشش`
export var chooseServiceAreaMap = `شهرهای تحت پوشش را انتخاب کنید`
export var numberOfSelectedRegions = `تعداد شهرهای انتخاب شده`
export var saturdayLabel = `شنبه`
export var sundayLabel = `یکشنبه`
export var mondayLabel = `دوشنبه`
export var tuesdayLabel = `سه شنبه`
export var wednesdayLabel = `چهار شنبه`
export var thursdayLabel = `پنجشنبه`
export var fridayLabel = `جمعه`
export var startWorkingHourLabel = `زمان شروع`
export var stopWorkingHourLabel = `زمان پایان`
export var workingDayLabel = `روز کاری`
export var wsDocument = `مدارک کسب و کار`
export var wrDocument = `مدارک متخصصین`
export var wsNew = `کسب و کارهای منتظر تایید اولیه`
export var ws4Doc = `کسب و کارهای منتظر مدارک`
export var ws4Area = `کسب و کارهای منتظر آدرس`
export var wrNew = `متخصصین منتظر تایید اولیه`
export var wr4Doc = `متخصصین منتظر مدارک`
export var finalOK = `تایید نهایی`
export var wsFinal = `کسب و کارهای منتظر تایید نهایی`
export var wrFinal = `متخصصین منتظر تایید نهایی`
export var wrProfileImage = `پروفایل متخصصین`
export var wsLogo = `لوگو جدید کسب و کار`
export var wsCatalog = `کاتالوگ جدبد کسب و کار`
export var showCartablDashboard = `نمایش کارتابل `
export var showCartableWorkStationDashboard = `نمایش کارتابل کسب و کارها`
export var showCartableWorkerDashboard = `نمایش کارتابل متخصصین`
export var confirmationLabel = `تایید/رد`
export var acceptLabel = `تایید`
export var rejectLabel = `رد`
export var waitToVerifyLabel  =`منتظر بررسی`
export var wsCartableLabel = `کارتابل کسب و کارها`
export var nwsCartableLabel = `کارتابل کسب و کارهای منتظر تایید اولیه`
export var nwsw4DocCartableLabel = `کارتابل کسب و کارهای منتظر مدرک `
export var nwsw4DocAreaCartableLabel = 'کارتابل کسب و کارهای منتظر مدارک و یا آدرس'
export var nwsw4AreaCartableLabel = `کارتابل کسب و کارهای منتظر آدرس `
export var fwsCartableLabel = `کارتابل کسب و کارهای منتظر تایید نهایی`
export var wrCartableLabel = `کارتابل متخصصین `
export var nwrCartableLabel = `کارتابل متخصصین منتظر تایید اولیه`
export var nwr4DocCartableLabel = `کارتابل متخصصین منتظر مدارک `
export var fwrCartableLabel = `کارتابل متخصصین منتظر تایید نهایی`
export var wsDocumentCartablLabel = `کارتابل مدارک کسب و کارها`
export var nwsDocumentCartablLabel = `کارتابل مدارک جدید کسب و کارها`
export var wrDocumentCartablLabel = `کارتابل مدارک متخصصین`
export var nwrDocumentCartablLabel = `کارتابل مدارک جدید متخصصین`
export var wrUsersProfileCartablLabel = `کارتابل تغییرات پروفایل متخصصین `
export var wrNewUsersProfileCartablLabel = `کارتابل تغییرات جدید پروفایل متخصصین `
export var itemsNeedToCheck = `موارد نیاز به بررسی`
export var wsLogosCartablLabel = `کارتابل تغییرات لوگو کسب و کارها `
export var wsNewLogosCartablLabel = `کارتابل تغییرات جدید لوگو کسب و کارها `
export var wsCatalogsCartablLabel = `کارتابل تغییرات تصاویر کاتالوگ کسب و کارها`
export var wsNewCatalogsCartablLabel = `کارتابل تغییرات جدید تصاویر کاتالوگ کسب و کارها`
export var expiredRequestCartableLabel = `درخواستهای منقضی`
export var historyLabel = `تاریخچه`
export var startTimeIsRequired = `تعیین زمان شروع ضروری است`
export var stopTimeIsRequired = `تعیین زمان پایان ضروری است`
export var clearFilterLabel = `پاک کردن فیلتر`
export var invalidLatMsg = `پارامتر عرض جغرافیایی نامعتبر است`
export var invalidLongMsg = `پارامتر طول جغرافیایی نامعتبر است`
export var priorityLabel = `اولویت`
export var requestLabel = ` درخواست`
export var requestCodeLabel = `کد درخواست`
export var suggestionLabel = `پیشنهادات`
export var requestStateHisoryLabel = `تاریخچه وضعیت`
export var acceptedSuggestionLabel = `پیشنهاد پذیرفته شده`

export var performaInvoiceLabel = `پیش فاکتور`
export var surveyFactorLabel = `فاکتور پس از بازدید`
export var finalFactorLabel = `فاکتور نهایی`
export var fullNameLabel = `نام و نام خانوادگی`
export var contactNumberLabel = `شماره تماس`
export var rcvTimeLabel = `زمان دریافت`
export var offerTimeLabel = `زمان ارایه پیشنهاد`
export var showRequestListLabel = `بروز رسانی لیست درخواست ها`
export var showTransactionListLabel = `بروز رسانی لیست تراکنش ها`
export var clientReviewPoints_PriceLabel = `امتیاز قیمت`
export var clientReviewPoints_TimeLabel = `امتیاز زمانبندی`
export var clientReviewPoints_WorkLabel = `امتیاز حسن انجام کار`
export var paymentTypeLabel = `نوع پرداخت`
export var paymentMethodLabel = `نحوه پرداخت`
export var totalPriceLabel = `مجموع قیمت`
export var priceLabel = `قیمت`
export var noSelectedSuggestionForRequestMsg = 'هنوز پیشنهادی برای این درخواست پذیرفته نشده است'
export var creditnLabel = 'اعتبار'
export var cacheLabel = `نقدی`
export var creditLabel  = `اعتبار جاری`
export var withCreditLabel  = `اعتباری`
export var periodTimeLabelx = `بازه زمانی `
export var registerPeriodTimeLabel = `بازه زمانی ثبت`
export var updatePeriodTimeLabel = `بازه زمانی بروز رسانی`
export var endTimePeriodLabel = 'بازه زمانی پایان'
export var requestPricePeriodLabel = `بازه قیمت` 
export var transactionAmountLabel = `بازه مبلغ` 
export var applyFilterLabel = `اعمال فیلتر`
export var notApplyFilterLabel = `عدم اعمال فیلتر`
export var clientLabel = `کاربر`
export var workerLabel = `متخصص`
export var factorDetailLabel = `نمایش اقلام فاکتور`
export var jobOfferListLabel = `لیست پیشنهادات درخواست`
export var backLabel = `بازگشت`
export var backToRequestList = `بازگشت به لیست درخواست ها`
export var candidateWorkerList = 'لیست ذخیره'
export var startTimeLabel = `زمان شروع`
export var endTimeLabel = `زمان پایان`
export var periodTimeLabel = `بازه زمانی شروع به کار`
export var allCurrentRequest = `همه درخواستهای جاری`
export var allFinishedRequest = `همه درخواستهای پایان یافته`
export var allRequests = `همه درخواستها`
export var emergancyLabel = `اورژانسی`
export var transferLabel = `هزینه رفت و آمد`
export var wageLabel = `دستمزد`
export var imagesLabel = `تصاویر`
export var snoozeLabel = `تعویق`
export var transactionLabel = `تراکنش های مالی`
export var amountLabel = `مبلغ تراکنش`
export var discountAmountLabel = 'مبلغ کد تخفیف'
export var rcvPaymentTypeLabel = `دریافت هزینه سرویس`;
export var sentPaymentTypeLabel = `پرداخت هزینه سرویس`;
export var trackingCodeLabel = `کد رهگیری`
export var accountNumberlabel = `شماره حساب شبا`
export var showTransactionList = `نمایش تراکنش ها`
export var registerFinancialDoc = `ثبت سند`
export var trackingCodeRequiredMsg = `فیلد کد رهگیری ضروری است`
export var amountRequired = `فیلد مبلغ ضروری است`
export var tomanLabel = `تومان`
export var minAmount = `حداقل مبلغ مجاز 1000 تومان است`
export var maxAmount = `حداکثر مبلغ مجاز 10000000 است`
export var sendSMSPanel = 'ارسال پیام کوتاه'
export var sendNotificationPanel = 'ارسال اعلان'
export var requiedFieldLabel = `این فیلد ضروری است`
export var maxCharLabel = `تعداد کاراکترهای وارد شده بیش از میزان مجاز است`
export var smsSendMsg = `پیام کوتاه ارسال شد`
export var clientApp = `برنامه کاربران`
export var workerApp = `برنامه متخصصین`
export var releaseTimeLabel = `زمان انتشار`
export var registerNewClientAppVersion = `ثبت نسخه جدید برنامه کاربران`
export var registerNewWorkerAppVersion = `ثبت نسخه جدید برنامه متخصصین`
export var reportedErrorCounter = `خطاهای گزارش شده`
export var show2Client = `نمایش به کاربر`
export var reqWait4Suggest = `منتظر پیشنهاد`
export var reqWait4Survey = `منتظر بازدید`
export var reqWait4SurveyAck = `منتظر تایید بازدید`
export var reqWait4Do = `منتظر اجرا`
export var reqWait4DoAck = `منتظر تایید شروع اجرا`
export var reqInProgress = `در حال اجرا`
export var reqWait4Payment = `منتظر پرداخت`
export var reqWait4Nazarsanji = `منتظر نظر سنجی`
export var reqSuggestFinished = `پایان مهلت ارایه پیشنهاد`
export var reqFinished = `پایان یافته `
export var reqCancelByC = `لغو شده توسط کاربر`
export var reqCancelByW = `لغو شده توسط متخصص`
export var reqCancelByO = `لغو شده توسط اپراتور`
export var registerPartLabel = ` ثبت نام`
export var workStationTitleLabel = `نام کسب و کار`
export var bizLabel = `کسب و کارها`
export var statJobCategory = `آمار کسب و کارها`
export var cartableDashboard = `داشبورد`
export var currentRequestsLabel = `درخواستهای جاری`
export var finishedRequestsLabel = `درخواستهای اتمام یافته`
export var waitTConfirm = `منتظر تایید`
export var noneLabel = `هیچکدام`
export var expiredLabel = `منقضی شده`
export var settingLabel = `تنظیمات`
export var valueLabel = `مقدار`
export var svalueLabel = `مقدار متنی`
export var fvalueLabel = `مقدار عددی`
export var unitLabel = `واحد`
export var suggestionStateLabel = `نتیجه بررسی کاربر`
export var offerStateLabel = `وضعیت پیشنهاد`
export var invalidInputMsg = `مقدار وارد شده صحیح نیست`
export var restrictedAccess = `شما مجاز به دسترسی به این بخش نیست`
export var selectNewCat3 = 'تخصص جدید را انتخاب کنید'
export var newCat3 = 'تخصص جدید'
export var currentCat3 = 'تخصص فعلی'
export var totalLabel = `جمع کل`
export var totalFactorLabel = `جمع کل فاکتور نهایی`
export var editDocMsg = `برای ویرایش نام و نوع مدرک بر روی فیلد مربوطه کلیک کنید و پس از ویرایشEnter کنید`
export var editCommisionOffsetMsg = `برای ویرایش آفست کمیسیون بر روی فیلد مربوطه کلیک کنید و پس از ویرایشEnter کنید`
export var noChangeMsg = `تغییری رخ نداده است`
export var todayLabel = `امروز`
export var fromLabel = `از`
export var taLabel = `تا`
export var controlLabel = `کنترلی`
export var appClientUsersLabel = `کاربران `
export var appWorkertUsersLabel = `متخصصین `
export var panelOperatorLabel = `کاربران پورتال`
export var lastPaymentTimeLabel = `آخرین زمان پرداخت`
export var payableAmountLabel = `مبلغ قابل پرداخت`
export var reportTimeLabel = `زمان گزارش`
export var getReportLabel = `تهیه گزارش`
export var sumReqPriceCash = `مجموع هزینه دریافتی سرویس بصورت نقدی`
export var sumReqPriceCredit = `مجموع هزینه دریافتی سرویس بصورت اعتباری`
export var sumBonous = `مجموع اعتبارات هدیه`
export var sumCommission = `مجموع کارمزد`
export var afterPaymentCredit = `اعتبار پس از تسویه`
export var filteredExcelViewLabel = `خروجی فیلتر شده متخصصین`
export var reminingCharsLabel = `تعداد کاراکترهای باقیمانده`
export var creditAfterPayment = `اعتبار پس از اعمال تراکنش`
export var registerTodayLabel = `ثبت نام امروز`
export var rollBackLabel = `رفع مغایرت`
export var pollTimeLabel = `زمان بروز رسانی ( 1 دقیقه) `
export var sumCreditIncrementLabel = `مجموع افزایش اعتبار`
export var sumCreditIncomeLabel = `مجموع درآمد بصورت اعتباری`
export var sumCreditOutcomeLabel = `مجموع پرداخت هزینه بصورت اعتباری`
export var sumCashIncomeLabel = `مجموع درآمد بصورت نقدی`
export var sumCashOutcomeLabel =  `مجموع پرداخت هزینه بصورت نقدی`
export var sumRollbackIncomeLabel = `مجموع اصلاحیه های درآمدی`
export var sumRollbackOutcomeLabel = `مجموع اصلاحیه های دریافتی`
export var sumPaymentLabel = `مجموع تسویه حساب`
export var appVersionLabel = `نسخه برنامه`
export var discountCodeMGMLabel = 'مدیریت کد تخفیف'
export var festivalMGMLabel = 'مدیریت مسابقه'
export var codeLabel = 'کد'
export var discountPercent = 'درصد تخفیف'
export var discountPercentPeriodLabel = 'بازه درصد تخفیف'
export var discountUsageLabel = 'مصرف کنندگان کد تخفیف'
export var maxCreditLabel = 'حداکثر اعتبار'
export var maxCreditPeriodLabel = 'بازه حداکثر اعتبار'
export var totalCounterLabel = 'تعداد کل'
export var totalCounterPeriodLabel = 'بازه تعداد کل'
export var usedCounterLabel = 'تعداد مصرفی'
export var usedCounterPeriodLabel = 'بازه تعداد مصرفی'
export var registerDiscount = 'ثبت کد تخفیف'
export var editDiscount = 'ویرایش کد تخفیف'
export var multiUseLabel = 'چند بار مصرف برای یک کاربر'
export var groupDiscountError = 'در ثبت گروهی بیش از یک کد تخفیف می بایست ثبت شود'
export var requiredMsgLabel = 'این فیلد اجباری است'
export var percentValidMsg = 'این فیلد باید بین عدد 0 تا 100 باشد'
export var jobCat1OnlySelectedMsg = 'می بایست شغل و تخصص نیز انتخاب شود'
export var commissionOnIvoiceItemsLabel = 'کارمزد اقلام فاکتور'
export var commissionOnWageLabel = 'کارمزد دستمزد'
export var commissionOnTransferLabel = 'کارمزد هزینه ایاب و ذهاب'
export var editCommissionLabel = 'ویرایش کارمزد'
export var editPriceLabel = 'ویرایش نرخ'
export var editActiveCityLabel = 'مدیریت شهرهای فعال برای سرویس دهی'
export var inActiveVerLabel = 'نسخه های غیر فعال'
export var activeVerLabel = 'نسخه های فعال'
export var registerUserStatLabel = 'آمار ثبت نام برنامه کاربر'
export var cancelFinishLabel = 'لغو/اتمام درخواست'
export var totalSuccessfullRequest = ' درخواستهای موفق'
export var totalFailSuccessfullRequest = ' درخواستهای ناموفق'
export var searchInJobCategory3 = 'جستجو در تخصص ها'
export var relatedCat = 'تخصص مرتبط'
export var imageNotSent = 'عکس ارسال نشده است'
export var notificationSentMsg = 'اعلان با موفقیت ارسال شده است'
export var followupLabel = 'اقدامات'
export var followUp = 'اقدام'
export var newFollowUp = 'اقدام جدید'
export var pointLabel = 'امتیاز'
export var deviceTypeLabel = 'نوع تجهیز'
export var sendTimeLabel = 'زمان ارسال'
export var notificationReportLabel = 'گزارش اعلان ها'
export var notificationsLabel = 'اعلان ها'
export var resultLabel = 'نتیجه'
export var wait4Init = 'منتظر تایید اولیه'
export var wait4Doc = 'منتظر مدارک و یا آدرس'
export var wait4Docx ='منتظر مدارک'
export var wait4Final = 'منتظر تایید نهایی'
export var wait4PreFinal = 'منتظر تایید نهایی کسب و کار'
export var netbarg = 'نت برگ'
export var questionScoreLabel = 'امتیاز سوالات';
export var invitationScoreLabel = 'امتیاز دعوت';
export var requestScoreLabel = 'امتیاز درخواست';
export var totalScoreLabel = 'مجموع امتیازات';
export var gradeLabel = 'رده';
export var todayInviteCntLabel = 'امتیاز امروز دعوت از دوستان'
export var lastConfirmTimeLabel = 'آخرین زمان تایید'
export var emergencyEnableLabel = 'اورژانسی'
export var nowToStartPeriodLabel = 'مهلت تا آغاز به کار'
export var invoiceRequiredLabel = 'ثبت فاکتور اجباری'
export var destinationAddressRequiredLabel = 'ثبت اجباری آدرس مقصد'
export var availableLabel = 'قابل دسترس'
export var timeLabel = 'زمان'
export var docLabel = 'نوع سند'
export var doc1Label = 'انجام درخواست'
export var doc3Label = 'افزایش اعتبار'
export var doc2Label = 'تسویه حساب'
export var docNumberLabel = 'شماره سند'
export var userCreditLabel = 'اعتبار کاربر'
export var discountCodeLabel = 'کد تخفیف'
export var commisionLabel = 'کارمزد(ریال)'
export var expertShareLabel = 'سهم متخصص'
export var incCreditValueLabel = 'مقدار افزایش اعتبار'
export var reckoningValueLabel = 'مقدار تسویه'
export var transactionListLabel = 'لیست تراکنش ها'
export var minCharMaxCharLabel = 'تعداد کاراکترهای مجاز بین 2 تا 40 کاراکتر است'
export var cancelCauseLabel = 'دلیل لغو'
export var discountSource = 'مرجع کد تخفیف'
export var discountType  = 'نوع کد تخفیف'
export var tempCode = 'ایجاد کد ورود موقت'
export var loginCode = 'کد ورود'
export var valueAddedLabel = 'ارزش افزوده'
export var valueAddredReportLabel = 'گزارش ارزش افزوده'
export var clientNameLabel = 'نام کاربر'
export var expertNameLabel = 'نام متخصص'
export var requestTypeLabel = 'نوع درخواست'
export var factorPriceLabel = 'مبلغ فاکتور'
export var showBillLabel = 'نمایش صورتحساب'
export var sellerInfoLabel = 'مشخصات فروشنده'
export var buyerInfoLabel = 'مشخصات خریدار'
export var productInfoLabel = 'مشخصات کالا/خدمات مورد معامله'
export var billInfoLabel = 'صورتحساب فروش کالا و خدمات'
export var addressLabel2 = 'نشانی'
export var legalPersonLabel = 'نام شخص حقوقی'
export var realPersonLabel = 'نام شخص حقیقی'
export var indexLabel = 'ردیف'
export var serviceTypeLabel = 'نوع خدمات'
export var orderLabel = 'سفارش'
export var totalLabel2 = 'مجموع'
export var totalTaxValueAdded = 'جمع مالیات، عوارض و ارزش افزوده (ریال)'
export var totalx = 'جمع مبلغ کل بعلاوه مالیات و عوارض (ریال)'