export class WorkerSearch {
	code: string;
	firstName: string;
	lastName: string;
	nationalCode: string;
	mobileNumber: string;
	active: boolean;
	provinceId: number;
	townshipId: number;
	cityId: number;
	regionId: number;
	areaId: number;
	jobCategory1Id: number;
	jobCategory2Id: number;
	jobCategory3Id: number;
	registerById: number;
	verified: number;
	verifyById: number;
	s_cityList: number[];
	registerTimeStart: string;
	registerTimeEnd: string;
	registerStateId: number;
	appVersion: string;
	offerBlock: boolean;
	haveBond: boolean;

	f_code: boolean = false;
	f_firstName: boolean = false;
	f_lastName: boolean = false;
	f_nationalCode: boolean = false;
	f_mobileNumber: boolean = false;
	f_active: boolean = false;
	f_provinceId: boolean = false;
	f_townshipId: boolean = false;
	f_cityId: boolean = false;
	f_regionId: boolean = false;
	f_areaId: boolean = false;
	f_jobCategory1Id: boolean = false;
	f_jobCategory2Id: boolean = false;
	f_jobCategory3Id: boolean = false;
	f_registerById: boolean = false;
	f_verified: boolean = false;
	f_verifyById: boolean = false;
	f_s_cityList: boolean = false;
	f_registerTime: boolean = false;
	f_registerStateId: boolean = false;
	f_appVersion: boolean = false;
	f_offerBlock = false;
	f_haveBond = false;
}