import { JobOffer } from 'app/entities/jobOffer.class';
import { BackendMessage } from '../entities/Msg.class';
import { RegisterState } from './registerState.class';
import { Request } from './request.class';
import { User } from './user.class';
import { WorkerDocument } from './workerDocument.class';
import { WorkerPhone } from './workerPhone.class';
import { WorkerScore } from './workerScore.class';
import { WorkerToJobsMap } from './workerToJobsMap.class';
import { WorkStation } from './workStation.class';
import { WorkTime } from './workTime.class';
import { WorkerToServiceCityMap } from './workerToServiceCityMap.class';

export class Worker {
	id: number;
	error: BackendMessage;
	code: string;
	accountNumber:string;
	workStation:WorkStation;
	user: User = new User();
	showCurrentLocation: boolean;
	workTime: WorkTime;
	workerScore: WorkerScore;
	active: boolean;
	regStateInfo:string;
	registerTimeS: string;
	registerTime: Date;
	registerBy: User;	
	projectCnt:number;
	projectCntLastMonth:number;
	todayOfferCnt:number;
	todaySuggestionCnt:number;
	todayPulseCnt:number;
	verified:number;
	verifyBy: User;
	verifyTimeS: string;
	updateTimeS:string;
	updateBy:User;
	workerPhones: WorkerPhone[] = [];
	workerToJobsMaps: WorkerToJobsMap[] = [];
	workerToServiceCityMaps : WorkerToServiceCityMap[] = [];
	jobOffers:JobOffer[];
	workerDocuments: WorkerDocument[] = [];
	requests: Request[] = [];
	deleted: boolean;
	deleteTimeS: string;	
	experienceStart: string;	
	score:number;
	registerState: RegisterState = new RegisterState();
	wsTitle:string;
	offerBlock:boolean;
	haveBond:boolean;
} 